# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'
            string $ibToken: '%env(IB_TOKEN)%'
            string $ibQueryId: '%env(IB_QUERY_ID)%'
            string $saxoAppKey: '%env(SAXO_APP_KEY)%'
            string $saxoAppSecret: '%env(SAXO_APP_SECRET)%'
            string $saxoRedirectUri: '%env(SAXO_REDIRECT_URI)%'
            string $saxoAuthEndpoint: '%env(SAXO_AUTH_ENDPOINT)%'
            string $saxoTokenEndpoint: '%env(SAXO_TOKEN_ENDPOINT)%'
            string $saxoApiBase: '%env(SAXO_API_BASE)%'

    App\:
        resource: '../src/'
